name: Build and Release
permission:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate build files
        run: dart run build_runner build

      - name: Run unit tests
        run: flutter test

  build_android:
    name: Build Android APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Generate build files
        run: dart run build_runner build

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v7
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build iOS Unsigned
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate build files
        run: dart run build_runner build

      - name: Build iOS xcarchive
        run: flutter build ipa --release --no-codesign

      - name: Compress xcarchive
        run: cd build/ios/archive && tar -czf Runner.xcarchive.tar.gz Runner.xcarchive

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v7
        with:
          name: ios-xcarchive
          path: build/ios/archive/Runner.xcarchive.tar.gz